CREATE DATABASE CURSO_DA_LM;
-- Esta instrucción genera la base de datos

USE CURSO_DA_LM;
-- Esta instrucción pone en uso la base de datos

CREATE TABLE CLIENTES (
	ID INT NOT NULL CHECK(ID>0) IDENTITY (1,1) PRIMARY KEY,
	NOMBRE VARCHAR(30) NOT NULL,
	CUIL_CUIT BIGINT UNIQUE CHECK(CUIL_CUIT>0) NOT NULL,
	FECHA_ALTA DATE DEFAULT(GETDATE()) NOT NULL,
	DIRECCION VARCHAR(50) NOT NULL,
	CIUDAD VARCHAR(25) NOT NULL,
	PROVINCIA VARCHAR(20) NOT NULL);

CREATE TABLE EMPLEADOS (
	ID INT NOT NULL CHECK(ID>0) IDENTITY(1,1) PRIMARY KEY,
	NOMBRE VARCHAR(30) NOT NULL,
	CUIL BIGINT UNIQUE CHECK(CUIL>0) NOT NULL,
	FECHA_INGRESO DATE NOT NULL,
	FECHA_NACIMIENTO DATE NOT NULL,
	MAIL VARCHAR(50) NOT NULL,
	AREA VARCHAR(20) NOT NULL);


CREATE TABLE CATEGORIAS (
	ID INT NOT NULL CHECK(ID>0) IDENTITY(1,1) PRIMARY KEY,
	NOMBRE VARCHAR(30) NOT NULL);

CREATE TABLE PROVEEDORES (
	ID INT NOT NULL CHECK(ID>0) IDENTITY(1,1) PRIMARY KEY,
	EMPRESA VARCHAR(40) UNIQUE NOT NULL,
	CUIT BIGINT UNIQUE CHECK(CUIT>0) NOT NULL,
	DIRECCION VARCHAR(50) NOT NULL,
	CIUDAD VARCHAR(30) NOT NULL);

CREATE TABLE PRODUCTOS (
	ID INT NOT NULL CHECK(ID>0) IDENTITY(1,1) PRIMARY KEY,
	NOMBRE VARCHAR(60) NOT NULL,
	PROVEEDOR_ID INT CHECK(PROVEEDOR_ID>0) NOT NULL,
	CATEGORIA_ID INT CHECK(CATEGORIA_ID>0) NOT NULL,
	COSTO MONEY CHECK(COSTO>0) NOT NULL,
	PRECIO_PUBLICO MONEY CHECK(PRECIO_PUBLICO>0) NOT NULL,
	STOCK INT CHECK(STOCK>0) NOT NULL,
	CONSTRAINT FK_PROVEEDOR_ID FOREIGN KEY (PROVEEDOR_ID)
	REFERENCES PROVEEDORES (ID)
	ON DELETE CASCADE 
	ON UPDATE CASCADE,
	CONSTRAINT FK_CATEGORIA_ID FOREIGN KEY (CATEGORIA_ID)
	REFERENCES CATEGORIAS (ID)
	ON DELETE CASCADE
	ON UPDATE CASCADE);
-- ON DELETE CASCADE: En el caso de eliminar una categoría
-- de la tabla CATEGORIAS, se eliminarían automáticamente
-- todos los productos que pertenezcan a esa categoría
-- ON UPDATE CASCADE: En el caso de modificar el ID de
-- una categoría en la tabla CATEGORIAS, ese mismo ID se 
-- actualizaría en la tabla PRODUCTOS.

CREATE TABLE VENTAS (
	ID INT NOT NULL CHECK(ID>0) IDENTITY (1,1) PRIMARY KEY,
	CLIENTE_ID INT CHECK(CLIENTE_ID>0) NOT NULL,
	CONSTRAINT FK_CLIENTE_ID FOREIGN KEY (CLIENTE_ID)
	REFERENCES CLIENTES (ID)
	ON UPDATE CASCADE,
	EMPLEADO_ID INT CHECK(EMPLEADO_ID>0) NOT NULL,
	CONSTRAINT FK_EMPLEADO_ID FOREIGN KEY (EMPLEADO_ID)
	REFERENCES EMPLEADOS (ID)
	ON UPDATE CASCADE,
	PRODUCTO_ID INT CHECK(PRODUCTO_ID>0) NOT NULL,
	CONSTRAINT FK_PRODUCTO_ID FOREIGN KEY (PRODUCTO_ID)
	REFERENCES PRODUCTOS (ID)
	ON UPDATE CASCADE,
	UNIDADES INT CHECK(UNIDADES>0) NOT NULL,
	DESCUENTO FLOAT CHECK(DESCUENTO>0) NOT NULL,
	TOTAL FLOAT CHECK(TOTAL>0) NOT NULL);
